const images = {
  backButton: require('./images/ui/backButton.png'),
  buttonBlue: require('./images/ui/buttonBlue.png'),
  buttonYellow: require('./images/ui/buttonYellow.png'),
  leftArrow: require('./images/ui/leftArrow.png'),
  levelChooserBg: require('./images/ui/levelChooserBg.png'),
  levelNumberContainer: require('./images/ui/levelNumberContainer.png'),
  mapButton: require('./images/ui/mapButton.png'),
  mapNavBackButton: require('./images/ui/mapNavBackButton.png'),
  mapTitleContainer: require('./images/ui/mapTitleContainer.png'),
  marker_1: require('./images/ui/marker_1.png'),
  marker_2: require('./images/ui/marker_2.png'),
  marker_3: require('./images/ui/marker_3.png'),
  marker_4: require('./images/ui/marker_4.png'),
  marker_5: require('./images/ui/marker_5.png'),
  marker_6: require('./images/ui/marker_6.png'),
  marker_7: require('./images/ui/marker_7.png'),
  marker_8: require('./images/ui/marker_8.png'),
  marker_9: require('./images/ui/marker_9.png'),
  navButtonBackgroundLeft: require('./images/ui/navButtonBackgroundLeft.png'),
  navButtonBackgroundRight: require('./images/ui/navButtonBackgroundRight.png'),
  ondori_logo: require('./images/ui/ondori_logo.png'),
  photoFrame: require('./images/ui/photoFrame.png'),
  rightArrow: require('./images/ui/rightArrow.png'),
  10001: require('./images/levels/10001.jpg'),
  10002: require('./images/levels/10002.jpg'),
  10003: require('./images/levels/10003.jpg'),
  10004: require('./images/levels/10004.jpg'),
  10005: require('./images/levels/10005.jpg'),
  10006: require('./images/levels/10006.jpg'),
  10007: require('./images/levels/10007.jpg'),
  10008: require('./images/levels/10008.jpg'),
  10009: require('./images/levels/10009.jpg')
}

export default images;
