const images = {
  'backButton': require('./ui/backButton.png'),
  'buttonYellow': require('./ui/buttonYellow.png'),
  'leftArrow': require('./ui/leftArrow.png'),
  'levelChooserBg': require('./ui/levelChooserBg.png'),
  'levelNumberContainer': require('./ui/levelNumberContainer.png'),
  'mapButton': require('./ui/mapButton.png'),
  'mapNavBackButton': require('./ui/mapNavBackButton.png'),
  'mapTitleContainer': require('./ui/mapTitleContainer.png'),
  'marker_1': require('./ui/marker_1.png'),
  'marker_2': require('./ui/marker_2.png'),
  'marker_3': require('./ui/marker_3.png'),
  'marker_4': require('./ui/marker_4.png'),
  'marker_5': require('./ui/marker_5.png'),
  'marker_6': require('./ui/marker_6.png'),
  'marker_7': require('./ui/marker_7.png'),
  'marker_8': require('./ui/marker_8.png'),
  'marker_9': require('./ui/marker_9.png'),
  'navButtonBackgroundLeft': require('./ui/navButtonBackgroundLeft.png'),
  'navButtonBackgroundRight': require('./ui/navButtonBackgroundRight.png'),
  'ondori_logo': require('./ui/ondori_logo.png'),
  'photoFrame': require('./ui/photoFrame.png'),
  'rightArrow': require('./ui/rightArrow.png'),
  '10001': require('./levels/10001.jpg'),
  '10002': require('./levels/10002.jpg'),
  '10003': require('./levels/10003.jpg'),
  '10004': require('./levels/10004.jpg'),
  '10005': require('./levels/10005.jpg'),
  '10006': require('./levels/10006.jpg'),
  '10007': require('./levels/10007.jpg'),
  '10008': require('./levels/10008.jpg'),
  '10009': require('./levels/10009.jpg')
}

export default images;
